# -*- coding: utf-8 -*-
"""chat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieHnXar6MD9J1xBL3Sd-uR2Q4D1qD459
"""

import os
import json
import falcon
from uuid import uuid4
import traceback

from middleware.auth_middleware import authenticate_user
from repositories import chat_repository

from resources.rag_mistral import RagMistralEngine


# Global RAG engine instance - loaded lazily on first use
_rag_engine = None
_rag_engine_error = None


def get_rag_engine():
    """
    Lazy initialization of RAG engine.
    Only loads on first call to avoid blocking server startup.
    """
    global _rag_engine, _rag_engine_error

    if _rag_engine is not None:
        return _rag_engine

    # If previous initialization failed, don't retry every time
    if _rag_engine_error is not None:
        raise RuntimeError(f"RAG engine failed to initialize: {_rag_engine_error}")

    try:
        print("[RAG] Initializing engine (first use)...")
        _rag_engine = RagMistralEngine()
        print("[RAG] ✓ Engine ready")
        return _rag_engine
    except Exception as e:
        _rag_engine_error = str(e)
        print(f"[RAG] ✗ Initialization failed: {e}")
        traceback.print_exc()
        raise


@falcon.before(authenticate_user)
class ChatResource:
    def __init__(self):
        self.server_domain = os.getenv("SERVER_DOMAIN", "http://localhost:8000")

    async def generate_stream(self, query, llm_client, conn, user_id, chat_id, release_conn):
        """
        Use RAG + Mistral to generate a streamed response.
        Handles errors gracefully and always releases the DB connection.
        """
        connection_released = False
        llm_chunks = []

        try:
            # Parse the query - handle both string and dict formats
            if isinstance(query, dict):
                # Try common keys that frontend might send
                query_str = (
                    query.get("prompt") or
                    query.get("message") or
                    query.get("content") or
                    query.get("query")
                )

                # If no standard key found, stringify the whole dict
                if not query_str:
                    query_str = json.dumps(query)
            else:
                query_str = str(query)

            # Clean and validate
            query_str = query_str.strip()
            if not query_str:
                error_msg = "Error: Empty query received"
                print(f"[CHAT] {error_msg}")
                yield error_msg.encode("utf-8")
                return

            print(f"[CHAT] Processing query: {query_str[:100]}...")

            # Get RAG engine (lazy load on first call)
            try:
                rag_engine = get_rag_engine()
            except Exception as e:
                error_msg = f"RAG system unavailable: {str(e)}"
                print(f"[CHAT] {error_msg}")
                yield error_msg.encode("utf-8")
                return

            # Build RAG-enhanced messages
            try:
                messages = rag_engine.build_messages(query_str)
            except Exception as e:
                print(f"[CHAT] RAG build_messages failed: {e}")
                # Fallback to simple message without RAG
                messages = [
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": query_str}
                ]

            # Stream response from Mistral
            try:
                stream = llm_client.chat.stream(
                    model="open-mistral-7b",
                    messages=messages,
                    stream=True,
                )

                for chunk in stream:
                    if chunk.data.choices and chunk.data.choices[0].delta.content:
                        piece = chunk.data.choices[0].delta.content
                        llm_chunks.append(piece)
                        yield piece.encode("utf-8")

            except Exception as e:
                error_msg = f"\n\nError during streaming: {str(e)}"
                print(f"[CHAT] {error_msg}")
                yield error_msg.encode("utf-8")
                return

            # Store full LLM response in database
            if llm_chunks:
                try:
                    llm_response = "".join(llm_chunks)
                    await chat_repository.create(conn, user_id, chat_id, llm_response)
                    print(f"[CHAT] Saved response to DB (chat_id={chat_id})")
                except Exception as e:
                    print(f"[CHAT] Failed to save response to DB: {e}")
                    # Don't yield error to user since they already got the response

        except Exception as e:
            error_msg = f"\n\nSorry, an unexpected error occurred: {str(e)}"
            print(f"[CHAT] Unexpected error in generate_stream: {e}")
            traceback.print_exc()
            yield error_msg.encode("utf-8")

        finally:
            # ALWAYS release the database connection
            if not connection_released:
                try:
                    await release_conn(conn)
                    connection_released = True
                    print(f"[CHAT] DB connection released (chat_id={chat_id})")
                except Exception as e:
                    print(f"[CHAT] Failed to release connection: {e}")

            # Signal end of stream
            yield None

    async def on_post(self, req, resp):
        """Create a new chat and generate first response"""
        # Check authentication
        if req.context.user_id is None:
            resp.status = falcon.HTTP_401
            resp.text = json.dumps({"error": "Unauthorized"})
            return

        try:
            # Parse query from request body
            prompt = await req.get_media()

            if not prompt:
                resp.status = falcon.HTTP_400
                resp.text = json.dumps({"error": "Empty prompt"})
                return

            chat_id = uuid4()
            print(f"[CHAT] New chat created: {chat_id}")

            # Disable automatic release of DB connection
            req.context.auto_release_conn = False

            # Store user prompt in chat history
            try:
                await chat_repository.create(
                    req.context.conn,
                    req.context.user_id,
                    chat_id,
                    prompt,
                )
            except Exception as e:
                print(f"[CHAT] Failed to store user prompt: {e}")
                resp.status = falcon.HTTP_500
                resp.text = json.dumps({"error": "Failed to save message"})
                await req.context.release_conn(req.context.conn)
                return

            # Generate response using RAG + Mistral
            resp.status = falcon.HTTP_201
            resp.set_header("access-control-expose-headers", "location")
            resp.set_header(
                "location",
                f"{self.server_domain}/api/v1/chat/{chat_id}",
            )
            resp.stream = self.generate_stream(
                prompt,
                req.context.llm_client,
                req.context.conn,
                req.context.user_id,
                chat_id,
                req.context.release_conn,
            )

        except Exception as e:
            print(f"[CHAT] Error in on_post: {e}")
            traceback.print_exc()
            resp.status = falcon.HTTP_500
            resp.text = json.dumps({"error": "Internal server error"})

    async def on_post_chat(self, req, resp, chat_id):
        """Add a message to existing chat and generate response"""
        # Check authentication
        if req.context.user_id is None:
            resp.status = falcon.HTTP_401
            resp.text = json.dumps({"error": "Unauthorized"})
            return

        try:
            # Parse query from request body
            prompt = await req.get_media()

            if not prompt:
                resp.status = falcon.HTTP_400
                resp.text = json.dumps({"error": "Empty prompt"})
                return

            # Check if the chat exists
            try:
                exists = await chat_repository.exists(
                    req.context.conn,
                    req.context.user_id,
                    chat_id,
                )
            except Exception as e:
                print(f"[CHAT] Error checking chat existence: {e}")
                resp.status = falcon.HTTP_500
                resp.text = json.dumps({"error": "Database error"})
                return

            if not exists:
                resp.status = falcon.HTTP_404
                resp.text = json.dumps({"error": "Chat not found"})
                return

            # Disable automatic release of DB connection
            req.context.auto_release_conn = False

            # Store user prompt in chat history
            try:
                await chat_repository.create(
                    req.context.conn,
                    req.context.user_id,
                    chat_id,
                    prompt,
                )
            except Exception as e:
                print(f"[CHAT] Failed to store user prompt: {e}")
                resp.status = falcon.HTTP_500
                resp.text = json.dumps({"error": "Failed to save message"})
                await req.context.release_conn(req.context.conn)
                return

            # Generate response using RAG + Mistral
            resp.status = falcon.HTTP_201
            resp.stream = self.generate_stream(
                prompt,
                req.context.llm_client,
                req.context.conn,
                req.context.user_id,
                chat_id,
                req.context.release_conn,
            )

        except Exception as e:
            print(f"[CHAT] Error in on_post_chat: {e}")
            traceback.print_exc()
            resp.status = falcon.HTTP_500
            resp.text = json.dumps({"error": "Internal server error"})

    async def on_get(self, req, resp):
        """Get all chats for current user"""
        # Check authentication
        if req.context.user_id is None:
            resp.status = falcon.HTTP_401
            resp.text = json.dumps({"error": "Unauthorized"})
            return

        try:
            # Fetch chat list
            chats = await chat_repository.get(
                req.context.conn,
                req.context.user_id,
            )

            resp.status = falcon.HTTP_200
            resp.content_type = "application/json"
            resp.text = json.dumps(chats)

        except Exception as e:
            print(f"[CHAT] Error in on_get: {e}")
            traceback.print_exc()
            resp.status = falcon.HTTP_500
            resp.text = json.dumps({"error": "Failed to fetch chats"})

    async def on_get_chat(self, req, resp, chat_id):
        """Get full conversation for a specific chat"""
        # Check authentication
        if req.context.user_id is None:
            resp.status = falcon.HTTP_401
            resp.text = json.dumps({"error": "Unauthorized"})
            return

        try:
            # Fetch full chat conversation
            chat = await chat_repository.get_chat(
                req.context.conn,
                req.context.user_id,
                chat_id,
            )

            if not chat:
                resp.status = falcon.HTTP_404
                resp.text = json.dumps({"error": "Chat not found"})
                return

            resp.status = falcon.HTTP_200
            resp.content_type = "application/json"
            resp.text = json.dumps(chat)

        except Exception as e:
            print(f"[CHAT] Error in on_get_chat: {e}")
            traceback.print_exc()
            resp.status = falcon.HTTP_500
            resp.text = json.dumps({"error": "Failed to fetch chat"})

    async def on_delete_chat(self, req, resp, chat_id):
        """Delete a specific chat"""
        # Check authentication
        if req.context.user_id is None:
            resp.status = falcon.HTTP_401
            resp.text = json.dumps({"error": "Unauthorized"})
            return

        try:
            # Delete chat
            deleted = await chat_repository.delete_chat(
                req.context.conn,
                req.context.user_id,
                chat_id,
            )

            if not deleted:
                resp.status = falcon.HTTP_404
                resp.text = json.dumps({"error": "Chat not found"})
            else:
                resp.status = falcon.HTTP_204

        except Exception as e:
            print(f"[CHAT] Error in on_delete_chat: {e}")
            traceback.print_exc()
            resp.status = falcon.HTTP_500
            resp.text = json.dumps({"error": "Failed to delete chat"})