# -*- coding: utf-8 -*-
"""rag_mistral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhV40IEAHn0fbj6eVxUB2uXF2p_9ZkGU
"""

# RAG engine for Mistral-7B:
# - Loads JSONL corpus
# - Cleans text
# - Builds BGE embeddings
# - Builds FAISS HNSW index
# - Retrieves top-k chunks
# - Builds system + user messages for Mistral

import subprocess
import sys


def install_if_missing(package, import_name=None):
    """
    Helper to install a package at runtime if it is missing.
    This is mainly for local/dev use so that the RAG code runs without
    asking people to manually pip install. In production, it is still
    better to manage dependencies via requirements.txt.
    """
    name = import_name or package
    try:
        __import__(name)
    except ImportError:
        print(f"[RAG] Missing '{package}', installing with pip...")
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", package])
        except Exception as e:
            print(f"[RAG] Failed to install {package}: {e}")
            raise


# Ensure required libraries are available
install_if_missing("sentence-transformers", "sentence_transformers")
install_if_missing("faiss-cpu", "faiss")

import os
import json
from typing import List, Dict

import numpy as np
import faiss
from sentence_transformers import SentenceTransformer


# Resolve the JSONL path relative to this file:
# server/src/resources/rag_mistral.py
# -> go up twice to server/, then into data/processed_data/
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
JSONL_FILE = os.path.abspath(
    os.path.join(
        BASE_DIR,
        "..",
        "..",
        "data",
        "processed_data",
        "rag_ready_docs_20251111.jsonl",
    )
)

EMBED_MODEL_NAME = "BAAI/bge-large-en-v1.5"
TOP_K = 8
QUERY_PREFIX = "Represent this sentence for searching relevant passages: "


def clean_text(raw: str) -> str:
    """
    Clean up the raw text field from the JSONL.
    Strips page_content/metadata wrappers and normalizes whitespace.
    """
    if not raw:
        return ""

    text = raw

    # Remove page_content wrapper if present
    if text.startswith("page_content='"):
        text = text[len("page_content='"):]
        if text.endswith("'"):
            text = text[:-1]

    # Remove metadata section
    if " metadata={" in text:
        text = text.split(" metadata={", 1)[0]

    # Normalize whitespace
    text = text.replace("\\n", " ").replace("\n", " ")
    text = " ".join(text.split())
    return text


def load_corpus(path: str) -> List[Dict]:
    """
    Load the RAG corpus from the JSONL file and return a list of:
      { "id": ..., "text": ..., "metadata": {...} }
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"[RAG] Corpus file not found: {path}")

    docs: List[Dict] = []
    line_num = 0

    try:
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line_num += 1
                if not line.strip():
                    continue

                try:
                    obj = json.loads(line)
                    text = clean_text(obj.get("text", ""))

                    if not text:
                        continue

                    docs.append({
                        "id": obj.get("id", f"doc_{line_num}"),
                        "text": text,
                        "metadata": obj.get("metadata", {}),
                    })
                except json.JSONDecodeError as e:
                    print(f"[RAG] Warning: Skipping invalid JSON at line {line_num}: {e}")
                    continue

    except Exception as e:
        raise RuntimeError(f"[RAG] Failed to load corpus from {path}: {e}")

    if not docs:
        raise ValueError(f"[RAG] No valid documents found in {path}")

    print(f"[RAG] Loaded {len(docs)} chunks from {path}")
    return docs


class RagMistralEngine:
    """
    RAG engine that:
      - encodes the corpus with BGE embeddings
      - builds a FAISS index
      - retrieves top-k chunks for a question
      - builds system+user messages for Mistral
    """

    def __init__(self, jsonl_file: str = JSONL_FILE, top_k: int = TOP_K):
        self.top_k = top_k
        self.corpus = []
        self.embed_model = None
        self.index = None

        try:
            # Load corpus
            print(f"[RAG] Initializing with corpus: {jsonl_file}")
            self.corpus = load_corpus(jsonl_file)

            # Load embedding model
            print(f"[RAG] Loading embedding model: {EMBED_MODEL_NAME}")
            print("[RAG] (This may take 30-60 seconds on first run...)")
            self.embed_model = SentenceTransformer(EMBED_MODEL_NAME)

            # Encode corpus
            texts = [QUERY_PREFIX + d["text"] for d in self.corpus]
            print(f"[RAG] Encoding {len(texts)} documents with BGE...")
            embeddings = self.embed_model.encode(
                texts,
                batch_size=32,
                show_progress_bar=True,
                convert_to_numpy=True,
                normalize_embeddings=True,
            )

            # Build FAISS index
            dim = embeddings.shape[1]
            print(f"[RAG] Building FAISS HNSW index (dimension={dim})...")
            index = faiss.IndexHNSWFlat(dim, 32)
            index.hnsw.efConstruction = 200
            index.hnsw.efSearch = 64
            index.add(embeddings)

            self.index = index
            print(f"[RAG] ✓ Index built successfully with {self.index.ntotal} vectors")

        except Exception as e:
            print(f"[RAG] ✗ Failed to initialize: {e}")
            raise RuntimeError(f"RAG engine initialization failed: {e}")

    def embed_query(self, question: str) -> np.ndarray:
        """
        Encode the user question into the same vector space as the corpus.
        """
        if not self.embed_model:
            raise RuntimeError("Embedding model not initialized")

        q = QUERY_PREFIX + question
        emb = self.embed_model.encode(
            [q],
            convert_to_numpy=True,
            normalize_embeddings=True,
        )
        return emb

    def retrieve(self, question: str) -> List[Dict]:
        """
        Retrieve top-k similar documents for the given question.
        Returns a list of dicts with text, id, metadata, and score.
        """
        if not self.index:
            raise RuntimeError("FAISS index not initialized")

        if not question or not question.strip():
            return []

        try:
            q_emb = self.embed_query(question)
            D, I = self.index.search(q_emb, self.top_k)

            results: List[Dict] = []
            for idx, score in zip(I[0], D[0]):
                if idx < 0 or idx >= len(self.corpus):
                    continue

                doc = self.corpus[idx]
                results.append({
                    "id": doc["id"],
                    "text": doc["text"],
                    "metadata": doc.get("metadata", {}),
                    "score": float(score),
                })
            return results

        except Exception as e:
            print(f"[RAG] Error during retrieval: {e}")
            return []

    def build_messages(self, question: str) -> List[Dict]:
        """
        Build system + user messages for Mistral's chat endpoint.
        The user message includes the retrieved context and the question.
        """
        if not question or not question.strip():
            # Return a basic message if question is empty
            return [
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": "Hello"}
            ]

        try:
            contexts = self.retrieve(question)

            if not contexts:
                # No context found - still answer but note the limitation
                system_content = (
                    "You are an MScAC interview mentor at the University of Toronto. "
                    "No relevant context was found for this question. "
                    "Provide a general answer and suggest the user contact the MScAC office "
                    "or check the official website for specific information."
                )
                user_content = f"Question:\n{question}\n"
            else:
                # Build context block with retrieved chunks
                context_lines = []
                for i, c in enumerate(contexts, start=1):
                    meta_items = c.get("metadata", {})
                    if meta_items:
                        meta = ", ".join(f"{k}={v}" for k, v in meta_items.items())
                        context_lines.append(f"[{i}] (id={c['id']}, {meta})\n{c['text']}\n")
                    else:
                        context_lines.append(f"[{i}] (id={c['id']})\n{c['text']}\n")

                context_block = "\n".join(context_lines)

                system_content = (
                    "You are an MScAC interview mentor at the University of Toronto. "
                    "Use only the provided context to answer. If the context does not contain "
                    "the answer, say you are not sure and suggest checking the MScAC office "
                    "or the official website.\n\n"
                    "Your answer must follow this structure:\n"
                    "1. Direct Answer\n"
                    "2. How to Prepare (numbered steps)\n"
                    "3. Sources (list the chunk IDs you used)\n"
                )

                user_content = (
                    f"Context:\n{context_block}\n\n"
                    f"Question:\n{question}\n"
                )

            messages = [
                {"role": "system", "content": system_content},
                {"role": "user", "content": user_content},
            ]
            return messages

        except Exception as e:
            print(f"[RAG] Error building messages: {e}")
            # Fallback to basic message
            return [
                {
                    "role": "system",
                    "content": "You are an MScAC interview mentor. Answer the question to the best of your ability."
                },
                {"role": "user", "content": question}
            ]